// realtime-modules/src/client/pipelines/index.ts
//
// Public barrel for @connorhoehn/realtime-modules/client/pipelines.
//
// Live pipeline-run status for a card in a conversation: `pipeline:event`
// frames over the gateway socket merged with platform-api's run snapshot.
// The REST helpers are pure (no React) so scripts and SSR can start and
// approve runs with the same code the hook uses.

export {
  usePipelineRunStatus,
  DEFAULT_STEP_LABELS,
  DEFAULT_PIPELINE_STEP_LABELS,
  DEFAULT_POLL_MS,
  DEFAULT_REVIEW_POLL_MS,
  runStatusDetail,
  reviewDetail,
  reviewOf,
  suggestionOf,
  isAwaitingReview,
  stepLabelFor,
  retryLabel,
  normalizeEventType,
  statusFromEvent,
  statusFromSnapshot,
  enrichTerminalStatus,
  detailsFromSnapshot,
  stepsFromSnapshot,
  stepTimelineLabel,
  opsFromApplyOutput,
  snippetFromOutline,
  documentFromOutputs,
  mergeDetails,
  requestPipelineRun,
  approvePipelineRun,
  reviewPipelineRun,
} from './usePipelineRunStatus';

export type {
  PipelineRunStatus,
  PipelineRunPhase,
  PipelineRunDecision,
  PipelineRunRef,
  PipelineRunSuggestion,
  PipelineRunReview,
  PipelineReviewDecision,
  PipelineRunDetails,
  PipelineRunStepDetail,
  PipelineRunStepStatus,
  // The element type of PipelineRunSnapshot.steps.
  PipelineSnapshotStep,
  PipelineRunOpDetail,
  PipelineRunDocumentDetail,
  PipelineRunRequestError,
  ReviewPipelineRunInput,
  ReviewPipelineRunResponse,
  PipelineRunSnapshot,
  PipelineRunTransport,
  StepLabelTables,
  UsePipelineRunStatusOptions,
} from './usePipelineRunStatus';

// v0.88.0 — the pipelines directory: one home for the work-type / kind enum,
// the last-run rollup, the status pill, and the hook that reads the catalog
// (`GET /api/pipelines/defs?include=rollup`) and keeps every row's rollup
// current from the `pipeline:all` run frames — no polling.
export {
  WORK_TYPE_LABEL,
  WORK_TYPE_ORDER,
  PIPELINE_KIND_ORDER,
  KIND_MARK,
  KIND_WORK_TYPE,
  KIND_LABEL,
  PIPELINE_KINDS,
  ORIGIN_KINDS,
  MAX_INSTRUCTION_CHARS,
  MAX_ROUTE_ENTRIES,
  RUN_ITEM_STATUSES,
  ROLLUP_RECENT_LIMIT,
  RECENT_LIMIT,
  RUN_EVENT_STATUS,
  emptyRollup,
  isWorkType,
  isPipelineKind,
  isFailedRunStatus,
  isActiveRunStatus,
  isTerminalRunStatus,
  workTypeOf,
  kindOf,
  summarize,
  summarizeAll,
  compareSummaries,
  sortSummaries,
  groupCatalog,
  groupByWorkType,
  relativeTime,
  statusPillFor,
  runEventFromFrame,
  applyRunEvent,
  mergeRunEvent,
} from './catalog';
export type {
  WorkType,
  PipelineWorkType,
  PipelineKind,
  PipelineDefinitionStatus,
  OriginKind,
  PipelineOrigin,
  DefinitionOrigin,
  InferredField,
  PipelineCatalogDefinition,
  RunItemStatus,
  RollupRunStatus,
  PipelineRunItemStatus,
  PipelineRunRollupItem,
  RollupRecentRun,
  PipelineRunRollup,
  PipelineCatalogEntry,
  PipelineDefinitionSummary,
  CatalogGroupBy,
  PipelineCatalogGroupCounts,
  PipelineCatalogGroup,
  PipelineStatusPillTone,
  PipelineStatusPill,
  RunRollupEvent,
  PipelineRunLifecycleEvent,
} from './catalog';
export {
  usePipelineCatalog,
  fetchPipelineCatalog,
  normalizeCatalogEntry,
  generatePipelineDraft,
  newPipelineDraftRequestId,
  PIPELINE_ALL_CHANNEL,
} from './usePipelineCatalog';
export type {
  PipelineCatalogRequestError,
  PipelineCatalogResponse,
  GeneratePipelineMode,
  GeneratePipelineDraftInput,
  GeneratePipelineDraftResponse,
  UsePipelineCatalogOptions,
  UsePipelineCatalogResult,
} from './usePipelineCatalog';
