// test/contract/contract-conformance.test.ts
//
// Wave A3 contract drift guard.
//
// Asserts — at COMPILE TIME — that this library's public types and the
// frames its hooks send/parse stay conformant with the canonical client-
// frame declarations generated by @connorhoehn/event-catalog (v0.3.55+,
// `client-frames` subpath: 25 outbound `client.<service>.<action>` frames
// + the inbound `ws.*` hook-contract declarations).
//
// How it runs:
//   - `npm run check:contract` — standalone tsc pass (tsconfig.contract.json).
//   - `npm test` — ts-jest type-checks this file on every suite run, so any
//     drift between the local types and the EC-generated unions fails CI-less
//     local runs too. The runtime `describe` block below is intentionally
//     trivial; the assertions are the types.
//
// Design notes:
//   - The library's public types in src/client/types.ts are deliberately NOT
//     aliased to EC types: event-catalog is a devDependency only, and the
//     built dist (.js and .d.ts) must stay free of event-catalog references
//     so consumers of the prebuilt dist need no new dependency. Conformance
//     is therefore asserted here instead of by aliasing.
//   - Outbound frames also carry inline `satisfies ClientFramePayload<...>`
//     annotations at every hook send-site, so send-site drift fails the main
//     build as well. This file additionally pins the FULL outbound frame-name
//     set, so a frame ADDED to (or removed from) event-catalog fails here and
//     forces an explicit decision in this library.
//   - EC inbound payloads model the PRE-PARSE wire (fields the gateway may
//     omit are optional); the local public types are POST-PARSE (the hooks'
//     as*() guards fill defaults, so fields are required). Full mutual
//     assignability is therefore asserted field-wise + by key-set parity,
//     not by whole-object assignability in the EC→local direction.

import type {
  ClientFramePayloadMap,
  ClientFramePayload,
  ChatOutboundFrame,
  PresenceOutboundFrame,
  ReactionOutboundFrame,
  ActivityOutboundFrame,
  CrdtOutboundFrame,
  FileuploadOutboundFrame,
  VideohangoutOutboundFrame,
  SubscribeOutboundFrame,
} from '@connorhoehn/event-catalog/client-frames';
import type { EventPayloadMap } from '@connorhoehn/event-catalog/types';

import type {
  ChatMessage,
  PresenceEntry,
  PresenceStatus,
  Reaction,
  ActivityEvent,
} from '../../src/client/types';
import type { HangoutParticipant } from '../../src/client/useVideoHangout';
import type { Notification } from '../../src/client/useNotifications';
import type { CapabilityDescriptor } from '../../src/client/useCapability';
import type { FileUploadState } from '../../src/client/useFileUpload';

// ---------------------------------------------------------------------------
// Assertion helpers
// ---------------------------------------------------------------------------

type Assert<T extends true> = T;
type Extends<A, B> = [A] extends [B] ? true : false;
/** Mutual assignability. */
type Equivalent<A, B> = Extends<A, B> extends true ? Extends<B, A> : false;
/** Strip string/number index signatures so declared keys can be compared. */
type RemoveIndex<T> = {
  [K in keyof T as string extends K ? never : number extends K ? never : K]: T[K];
};
/** Exact key-set parity between two object types. */
type SameKeys<A, B> = Equivalent<keyof A, keyof B>;

// ---------------------------------------------------------------------------
// 1. Outbound frame-name coverage — pins the full ClientFramePayloadMap.
//
// If event-catalog ADDS an outbound client frame, `_outboundNamesPinned`
// fails until this library either implements the frame or consciously lists
// it here. If EC REMOVES/renames one, the per-frame assertions below fail.
// ---------------------------------------------------------------------------

type ExpectedOutboundFrameName =
  | 'client.chat.subscribe'
  | 'client.chat.send'
  | 'client.chat.history'
  | 'client.presence.subscribe'
  | 'client.presence.unsubscribe'
  | 'client.presence.set'
  | 'client.reaction.react'
  | 'client.activity.subscribe'
  | 'client.activity.unsubscribe'
  | 'client.activity.history'
  | 'client.crdt.subscribe'
  | 'client.crdt.unsubscribe'
  | 'client.crdt.update'
  | 'client.crdt.awareness'
  | 'client.fileupload.request-upload'
  | 'client.fileupload.complete'
  | 'client.fileupload.cancel'
  | 'client.videohangout.start'
  | 'client.videohangout.join'
  | 'client.videohangout.leave'
  | 'client.videohangout.end'
  | 'client.videohangout.toggle-video'
  | 'client.videohangout.toggle-audio'
  | 'client.subscribe.subscribe'
  | 'client.subscribe.unsubscribe';

type _outboundNamesPinned = Assert<
  Equivalent<keyof ClientFramePayloadMap, ExpectedOutboundFrameName>
>;

// ---------------------------------------------------------------------------
// 2. Outbound frames — representative shapes of what each hook actually
// sends, asserted MUTUALLY assignable with the EC payload (the EC payloads
// carry `[key: string]: unknown`, so the reverse direction holds whenever
// the declared fields agree).
//
// Send-sites carrying the same shapes are additionally annotated with
// `satisfies` in: useChat, usePresence, useReactions, useActivity,
// useFileUpload, useVideoHangout, useCRDT, useYjsDoc, useWebSocket,
// GatewaySocketProvider, GatewayProvider.
// ---------------------------------------------------------------------------

// chat (useChat + GatewaySocketProvider feature auto-subscribe)
type LocalChatSubscribe = { service: 'chat'; action: 'subscribe'; channel?: string };
type LocalChatSend = { service: 'chat'; action: 'send'; channel: string; message: string };
type LocalChatHistory = { service: 'chat'; action: 'history'; channel: string; limit: number };
type _chatSub = Assert<Extends<LocalChatSubscribe, ClientFramePayload<'client.chat.subscribe'>>>;
type _chatSend = Assert<Equivalent<LocalChatSend, Required<RemoveIndex<ClientFramePayload<'client.chat.send'>>>>>;
type _chatHist = Assert<Equivalent<LocalChatHistory, Required<RemoveIndex<ClientFramePayload<'client.chat.history'>>>>>;
type _chatUnion = Assert<Extends<LocalChatSend | LocalChatHistory | LocalChatSubscribe, ChatOutboundFrame>>;

// presence (usePresence + GatewaySocketProvider feature auto-subscribe)
type LocalPresenceSubscribe = { service: 'presence'; action: 'subscribe'; channel?: string };
type LocalPresenceUnsubscribe = { service: 'presence'; action: 'unsubscribe'; channel: string };
type LocalPresenceSetStatus = { service: 'presence'; action: 'set'; channel: string; status: PresenceStatus };
type LocalPresenceSetMetadata = { service: 'presence'; action: 'set'; channel: string; metadata: Record<string, unknown> };
type _presSub = Assert<Extends<LocalPresenceSubscribe, ClientFramePayload<'client.presence.subscribe'>>>;
type _presUnsub = Assert<Extends<LocalPresenceUnsubscribe, ClientFramePayload<'client.presence.unsubscribe'>>>;
type _presSetA = Assert<Extends<LocalPresenceSetStatus, ClientFramePayload<'client.presence.set'>>>;
type _presSetB = Assert<Extends<LocalPresenceSetMetadata, ClientFramePayload<'client.presence.set'>>>;
type _presUnion = Assert<
  Extends<LocalPresenceSubscribe | LocalPresenceUnsubscribe | LocalPresenceSetStatus, PresenceOutboundFrame>
>;

// reaction (useReactions.react — the hook's ONLY outbound frame; there is no
// outbound reaction-history request, see useReactions header)
type LocalReactionReact = {
  service: 'reaction';
  action: 'react';
  channel: string;
  emoji: string;
  targetId?: string;
  metadata?: Record<string, unknown>;
};
type _react = Assert<Equivalent<LocalReactionReact, RemoveIndex<ClientFramePayload<'client.reaction.react'>>>>;
type _reactUnion = Assert<Extends<LocalReactionReact, ReactionOutboundFrame>>;

// activity (useActivity)
type LocalActivitySubscribe = { service: 'activity'; action: 'subscribe'; channel: string };
type LocalActivityUnsubscribe = { service: 'activity'; action: 'unsubscribe'; channel: string };
type LocalActivityHistory = { service: 'activity'; action: 'history'; channel: string; limit: number };
type _actSub = Assert<Equivalent<LocalActivitySubscribe, RemoveIndex<ClientFramePayload<'client.activity.subscribe'>>>>;
type _actUnsub = Assert<Equivalent<LocalActivityUnsubscribe, RemoveIndex<ClientFramePayload<'client.activity.unsubscribe'>>>>;
type _actHist = Assert<Equivalent<LocalActivityHistory, RemoveIndex<ClientFramePayload<'client.activity.history'>>>>;
type _actUnion = Assert<
  Extends<LocalActivitySubscribe | LocalActivityUnsubscribe | LocalActivityHistory, ActivityOutboundFrame>
>;

// crdt (useCRDT / useYjsDoc / GatewayProvider)
type LocalCrdtSubscribe = { service: 'crdt'; action: 'subscribe'; channel: string };
type LocalCrdtUnsubscribe = { service: 'crdt'; action: 'unsubscribe'; channel: string };
type LocalCrdtUpdate = { service: 'crdt'; action: 'update'; channel: string; update: string };
// Canonical awareness frame. NOTE: GatewayProvider's send-site forwards
// `mode` as plain `string` (useAwarenessState.updateMode accepts any string);
// the canonical declaration narrows it to the union below. Narrowing the
// call-site would be a wire change (dropping non-standard modes), so the
// looseness is documented here instead of "fixed".
type LocalCrdtAwareness = {
  service: 'crdt';
  action: 'awareness';
  channel: string;
  update: string;
  mode?: 'editor' | 'reviewer' | 'reader';
  idle?: boolean;
};
type _crdtSub = Assert<Equivalent<LocalCrdtSubscribe, RemoveIndex<ClientFramePayload<'client.crdt.subscribe'>>>>;
type _crdtUnsub = Assert<Equivalent<LocalCrdtUnsubscribe, RemoveIndex<ClientFramePayload<'client.crdt.unsubscribe'>>>>;
type _crdtUpdate = Assert<Equivalent<LocalCrdtUpdate, RemoveIndex<ClientFramePayload<'client.crdt.update'>>>>;
type _crdtAwareness = Assert<Equivalent<LocalCrdtAwareness, RemoveIndex<ClientFramePayload<'client.crdt.awareness'>>>>;
type _crdtUnion = Assert<
  Extends<LocalCrdtSubscribe | LocalCrdtUnsubscribe | LocalCrdtUpdate | LocalCrdtAwareness, CrdtOutboundFrame>
>;

// fileupload (useFileUpload)
type LocalFileuploadRequest = {
  service: 'fileupload';
  action: 'request-upload';
  channel: string;
  id: string;
  filename: string;
  size: number;
  metadata?: Record<string, unknown>;
};
type LocalFileuploadComplete = { service: 'fileupload'; action: 'complete'; channel: string; id: string };
type LocalFileuploadCancel = { service: 'fileupload'; action: 'cancel'; channel: string; id: string };
type _fupReq = Assert<Equivalent<LocalFileuploadRequest, RemoveIndex<ClientFramePayload<'client.fileupload.request-upload'>>>>;
type _fupDone = Assert<Equivalent<LocalFileuploadComplete, RemoveIndex<ClientFramePayload<'client.fileupload.complete'>>>>;
type _fupCancel = Assert<Equivalent<LocalFileuploadCancel, RemoveIndex<ClientFramePayload<'client.fileupload.cancel'>>>>;
type _fupUnion = Assert<
  Extends<LocalFileuploadRequest | LocalFileuploadComplete | LocalFileuploadCancel, FileuploadOutboundFrame>
>;

// videohangout (useVideoHangout)
type LocalHangoutStart = {
  service: 'videohangout';
  action: 'start';
  channel: string;
  type?: 'hangout' | 'call';
  metadata?: Record<string, unknown>;
};
type LocalHangoutJoin = { service: 'videohangout'; action: 'join'; channel: string; sessionId: string };
type LocalHangoutLeave = { service: 'videohangout'; action: 'leave'; channel: string; sessionId: string };
type LocalHangoutEnd = { service: 'videohangout'; action: 'end'; channel: string; sessionId: string };
type LocalHangoutToggleVideo = {
  service: 'videohangout';
  action: 'toggle-video';
  channel: string;
  sessionId: string;
  videoOn: boolean;
};
type LocalHangoutToggleAudio = {
  service: 'videohangout';
  action: 'toggle-audio';
  channel: string;
  sessionId: string;
  audioOn: boolean;
};
type _vhStart = Assert<Equivalent<LocalHangoutStart, RemoveIndex<ClientFramePayload<'client.videohangout.start'>>>>;
type _vhJoin = Assert<Equivalent<LocalHangoutJoin, RemoveIndex<ClientFramePayload<'client.videohangout.join'>>>>;
type _vhLeave = Assert<Equivalent<LocalHangoutLeave, RemoveIndex<ClientFramePayload<'client.videohangout.leave'>>>>;
type _vhEnd = Assert<Equivalent<LocalHangoutEnd, RemoveIndex<ClientFramePayload<'client.videohangout.end'>>>>;
type _vhTv = Assert<Equivalent<LocalHangoutToggleVideo, RemoveIndex<ClientFramePayload<'client.videohangout.toggle-video'>>>>;
type _vhTa = Assert<Equivalent<LocalHangoutToggleAudio, RemoveIndex<ClientFramePayload<'client.videohangout.toggle-audio'>>>>;
type _vhUnion = Assert<
  Extends<
    | LocalHangoutStart
    | LocalHangoutJoin
    | LocalHangoutLeave
    | LocalHangoutEnd
    | LocalHangoutToggleVideo
    | LocalHangoutToggleAudio,
    VideohangoutOutboundFrame
  >
>;

// subscribe multiplexer (useWebSocket subscribe/unsubscribe + auto-resubscribe)
type LocalGenericSubscribe = { service: 'subscribe'; action: 'subscribe'; channel: string };
type LocalGenericUnsubscribe = { service: 'subscribe'; action: 'unsubscribe'; channel: string };
type _genSub = Assert<Equivalent<LocalGenericSubscribe, RemoveIndex<ClientFramePayload<'client.subscribe.subscribe'>>>>;
type _genUnsub = Assert<Equivalent<LocalGenericUnsubscribe, RemoveIndex<ClientFramePayload<'client.subscribe.unsubscribe'>>>>;
type _genUnion = Assert<Extends<LocalGenericSubscribe | LocalGenericUnsubscribe, SubscribeOutboundFrame>>;

// ---------------------------------------------------------------------------
// 3. Inbound hook-contract frames — the 12 ws.* declarations EC added for
// the hook contracts (presence:joined/left, fileupload:*, videohangout:*,
// notification:*, capability/feature-flag updated).
// ---------------------------------------------------------------------------

// presence:joined → PresenceEntry (usePresence roster entries).
// EC `client` is pre-parse (only clientId required, status is plain string);
// PresenceEntry is post-parse (asPresenceEntry fills defaults, status is the
// documented PresenceStatus vocabulary). Assert key parity + local→EC.
type EcPresenceJoinedClient = RemoveIndex<EventPayloadMap['ws.presence.joined']['client']>;
type _presenceEntryKeys = Assert<SameKeys<PresenceEntry, EcPresenceJoinedClient>>;
type _presenceEntryFields = Assert<Extends<PresenceEntry, EcPresenceJoinedClient>>;
type _presenceStatusIsString = Assert<Extends<PresenceStatus, EcPresenceJoinedClient['status']>>;

// presence:left → { channel, clientId } (usePresence removal path).
type EcPresenceLeft = EventPayloadMap['ws.presence.left'];
type _presenceLeft = Assert<Extends<{ type: 'presence:left'; channel: string; clientId: string }, EcPresenceLeft>>;

// fileupload:progress / scanning / cancelled → fields useFileUpload reads.
type EcFupProgress = EventPayloadMap['ws.fileupload.progress'];
type _fupProgId = Assert<Extends<EcFupProgress['id'], string>>;
type _fupProgPct = Assert<Extends<EcFupProgress['progress'], FileUploadState['progress'] & number>>;
type _fupScanning = Assert<Extends<EventPayloadMap['ws.fileupload.scanning']['id'], string>>;
type _fupCancelled = Assert<Extends<EventPayloadMap['ws.fileupload.cancelled']['id'], string>>;

// videohangout:participant → HangoutParticipant.
// Same pre/post-parse split: EC marks videoOn/audioOn/joinedAt optional on
// the wire; asParticipant() defaults them, so they are required locally.
type EcHangoutParticipant = RemoveIndex<EventPayloadMap['ws.videohangout.participant']['participant']>;
type _participantKeys = Assert<SameKeys<HangoutParticipant, EcHangoutParticipant>>;
type _participantFields = Assert<Extends<HangoutParticipant, EcHangoutParticipant>>;
type _participantRole = Assert<Equivalent<HangoutParticipant['role'], EcHangoutParticipant['role']>>;

// videohangout:media → media-toggle fanout fields.
type EcHangoutMedia = EventPayloadMap['ws.videohangout.media'];
type _media = Assert<
  Extends<
    { type: 'videohangout:media'; channel: string; clientId: string; videoOn: boolean; audioOn: boolean },
    EcHangoutMedia
  >
>;

// notification:new / read / bulk-update → Notification (useNotifications).
type EcNotificationPayload = RemoveIndex<EventPayloadMap['ws.notification.new']['payload']>;
type _notificationKeys = Assert<SameKeys<Notification, EcNotificationPayload>>;
type _notificationFields = Assert<Extends<Notification, EcNotificationPayload>>;
type _notificationRead = Assert<Extends<EventPayloadMap['ws.notification.read']['payload']['id'], string>>;
type EcBulkNotification = RemoveIndex<
  EventPayloadMap['ws.notification.bulk-update']['payload']['notifications'][number]
>;
type _notificationBulk = Assert<Extends<Notification, EcBulkNotification>>;

// capability:updated → CapabilityDescriptor (useCapability).
type EcCapabilityPayload = RemoveIndex<EventPayloadMap['ws.capability.updated']['payload']>;
type _capabilityKeys = Assert<SameKeys<CapabilityDescriptor, EcCapabilityPayload>>;
type _capability = Assert<Equivalent<CapabilityDescriptor, EcCapabilityPayload>>;

// feature-flag:updated → useFeatureFlag's (module-private) payload mirror.
type LocalFeatureFlagPayload = {
  name: string;
  enabled: boolean;
  variant?: string;
  metadata?: Record<string, unknown>;
};
type _featureFlag = Assert<Equivalent<LocalFeatureFlagPayload, RemoveIndex<EventPayloadMap['ws.feature-flag.updated']['payload']>>>;

// ---------------------------------------------------------------------------
// 4. Known divergences (documented, deliberately NOT "fixed" in Wave A3 —
// each fix would be a runtime behavior change, not a doc/type correction).
//
// a) useActivity inbound envelope. The hook parses
//      { type: 'activity:event', channel, ...ActivityEvent }   (flat)
//      { type: 'activity:history', channel, events: [...] }
//    but EC ground truth (matching the gateway's lifted ActivityService) is
//      { type: 'activity:event', payload: { eventType, detail, ... } }
//      { type: 'activity', action: 'history', events, channelId }
//    and the activity:event broadcast carries NO channel field. The
//    ActivityEvent FIELD shape itself matches EC (asserted below); only the
//    envelope diverges. Reconciling the hook is a parser behavior change —
//    flagged for a follow-up wave, see the A3 session report.
//
// b) useChat / useReactions inbound envelopes (chat:message / chat:history /
//    reaction:new / reaction:history, all flat) have NO hook-contract EC
//    declarations; the existing ws.chat.* / ws.reaction.* declarations
//    describe the gateway's `type:'chat'` / `type:'reaction'` action-frame
//    envelopes ("naming tension documented per Wave A2, not renamed").
//    Nothing to assert until EC declares the hook-contract frames or the
//    hooks adopt the gateway envelope.
//
// c) usePresence's presence:state / presence:updated inbound frames are not
//    yet declared in EC (only presence:joined / presence:left were added).
// ---------------------------------------------------------------------------

// ActivityEvent field shape vs EC's ws.activity.event payload (post-parse →
// pre-parse direction + key parity), envelope divergence notwithstanding.
type EcActivityEventPayload = RemoveIndex<EventPayloadMap['ws.activity.event']['payload']>;
type _activityKeys = Assert<SameKeys<ActivityEvent, EcActivityEventPayload>>;
type _activityFields = Assert<Extends<ActivityEvent, EcActivityEventPayload>>;

// Reaction core wire fields vs the legacy ws.reaction.received data block —
// partial check only (see divergence note b).
type EcReactionData = RemoveIndex<EventPayloadMap['ws.reaction.received']['data']>;
type _reactionCore = Assert<Extends<Reaction, EcReactionData>>;

// ChatMessage has no EC counterpart to assert against (divergence note b);
// referenced here so the import stays load-bearing if the type is renamed.
type _chatMessageStillExported = Assert<Extends<ChatMessage['id'], string>>;

// ---------------------------------------------------------------------------
// Runtime stub — keeps jest happy; the real assertions are the types above.
// A representative frame per service exercises that the EC types describe
// constructible values (and that the type-only imports erased at runtime).
// ---------------------------------------------------------------------------

describe('contract conformance (compile-time)', () => {
  it('EC client-frame payloads are constructible from hook frame shapes', () => {
    const chatSend: ClientFramePayload<'client.chat.send'> = {
      service: 'chat',
      action: 'send',
      channel: 'chat:general',
      message: 'hello',
    };
    const react: ClientFramePayload<'client.reaction.react'> = {
      service: 'reaction',
      action: 'react',
      channel: 'chat:general',
      emoji: '🔥',
    };
    const resub: ClientFramePayload<'client.subscribe.subscribe'> = {
      service: 'subscribe',
      action: 'subscribe',
      channel: 'doc:readme',
    };
    expect(chatSend.service).toBe('chat');
    expect(react.action).toBe('react');
    expect(resub.channel).toBe('doc:readme');
  });

  it('type-only event-catalog imports leave no runtime require', () => {
    // If the import at the top of this file were not type-only, jest's
    // module registry would contain the EC package after loading this file.
    const ecRuntime = Object.keys(require.cache).filter((k) =>
      k.includes(`${'@connorhoehn'}/event-catalog`),
    );
    expect(ecRuntime).toEqual([]);
  });
});
