// test/contract/contract-conformance.test.ts
//
// Wave A3 contract drift guard.
//
// Asserts — at COMPILE TIME — that this library's public types and the
// frames its hooks send/parse stay conformant with the canonical client-
// frame declarations generated by @connorhoehn/event-catalog (v0.3.58+,
// `client-frames` subpath: 31 outbound `client.<service>.<action>` frames
// + the inbound `ws.*` hook-contract + gateway send-back declarations). EC
// v0.3.58 declared the gateway send-back envelopes per service ground truth
// (divergence note b); §3b asserts the hooks' parsers against them. EC v0.3.56
// corrected
// the chat/presence/reaction/activity declarations against gateway service
// ground truth (hub#1497): chat verb is 'join' (not 'subscribe'), reaction
// verb is 'send' (not 'react'), presence.subscribe requires channel,
// presence.set requires status (channel deprecated; pinning via channels[]),
// chat.history limit optional, activity keyed on channelId with verb
// 'getHistory'. EC v0.3.57 backfilled the remaining gateway-verified verbs
// (chat.leave, reaction.subscribe/unsubscribe/getAvailable,
// presence.get/heartbeat), so every verb in the verified handleAction sets
// is now declared and asserted below.
//
// How it runs:
//   - `npm run check:contract` — standalone tsc pass (tsconfig.contract.json).
//   - `npm test` — ts-jest type-checks this file on every suite run, so any
//     drift between the local types and the EC-generated unions fails CI-less
//     local runs too. The runtime `describe` block below is intentionally
//     trivial; the assertions are the types.
//
// Design notes:
//   - The library's public types in src/client/types.ts are deliberately NOT
//     aliased to EC types: event-catalog is a devDependency only, and the
//     built dist (.js and .d.ts) must stay free of event-catalog references
//     so consumers of the prebuilt dist need no new dependency. Conformance
//     is therefore asserted here instead of by aliasing.
//   - Outbound frames also carry inline `satisfies ClientFramePayload<...>`
//     annotations at every hook send-site, so send-site drift fails the main
//     build as well. This file additionally pins the FULL outbound frame-name
//     set, so a frame ADDED to (or removed from) event-catalog fails here and
//     forces an explicit decision in this library.
//   - EC inbound payloads model the PRE-PARSE wire (fields the gateway may
//     omit are optional); the local public types are POST-PARSE (the hooks'
//     as*() guards fill defaults, so fields are required). Full mutual
//     assignability is therefore asserted field-wise + by key-set parity,
//     not by whole-object assignability in the EC→local direction.

import type {
  ClientFramePayloadMap,
  ClientFramePayload,
  ChatOutboundFrame,
  PresenceOutboundFrame,
  ReactionOutboundFrame,
  ActivityOutboundFrame,
  CrdtOutboundFrame,
  FileuploadOutboundFrame,
  VideohangoutOutboundFrame,
  SubscribeOutboundFrame,
} from '@connorhoehn/event-catalog/client-frames';
import type { EventPayloadMap } from '@connorhoehn/event-catalog/types';

import type {
  ChatMessage,
  PresenceEntry,
  PresenceStatus,
  Reaction,
  ActivityEvent,
} from '../../src/client/types';
import type { HangoutParticipant } from '../../src/client/useVideoHangout';
import type { Notification } from '../../src/client/useNotifications';
import type { CapabilityDescriptor } from '../../src/client/useCapability';
import type { FileUploadState } from '../../src/client/useFileUpload';

// ---------------------------------------------------------------------------
// Assertion helpers
// ---------------------------------------------------------------------------

type Assert<T extends true> = T;
type Extends<A, B> = [A] extends [B] ? true : false;
/** Mutual assignability. */
type Equivalent<A, B> = Extends<A, B> extends true ? Extends<B, A> : false;
/** Strip string/number index signatures so declared keys can be compared. */
type RemoveIndex<T> = {
  [K in keyof T as string extends K ? never : number extends K ? never : K]: T[K];
};
/** Exact key-set parity between two object types. */
type SameKeys<A, B> = Equivalent<keyof A, keyof B>;

// ---------------------------------------------------------------------------
// 1. Outbound frame-name coverage — pins the full ClientFramePayloadMap.
//
// If event-catalog ADDS an outbound client frame, `_outboundNamesPinned`
// fails until this library either implements the frame or consciously lists
// it here. If EC REMOVES/renames one, the per-frame assertions below fail.
// ---------------------------------------------------------------------------

type ExpectedOutboundFrameName =
  | 'client.chat.join'
  | 'client.chat.leave'
  | 'client.chat.send'
  | 'client.chat.history'
  | 'client.presence.subscribe'
  | 'client.presence.unsubscribe'
  | 'client.presence.set'
  | 'client.presence.get'
  | 'client.presence.heartbeat'
  | 'client.reaction.subscribe'
  | 'client.reaction.unsubscribe'
  | 'client.reaction.send'
  | 'client.reaction.getAvailable'
  | 'client.activity.subscribe'
  | 'client.activity.unsubscribe'
  | 'client.activity.getHistory'
  | 'client.crdt.subscribe'
  | 'client.crdt.unsubscribe'
  | 'client.crdt.update'
  | 'client.crdt.awareness'
  | 'client.fileupload.request-upload'
  | 'client.fileupload.complete'
  | 'client.fileupload.cancel'
  | 'client.videohangout.start'
  | 'client.videohangout.join'
  | 'client.videohangout.leave'
  | 'client.videohangout.end'
  | 'client.videohangout.toggle-video'
  | 'client.videohangout.toggle-audio'
  | 'client.subscribe.subscribe'
  | 'client.subscribe.unsubscribe';

type _outboundNamesPinned = Assert<
  Equivalent<keyof ClientFramePayloadMap, ExpectedOutboundFrameName>
>;

// ---------------------------------------------------------------------------
// 2. Outbound frames — representative shapes of what each hook actually
// sends, asserted MUTUALLY assignable with the EC payload (the EC payloads
// carry `[key: string]: unknown`, so the reverse direction holds whenever
// the declared fields agree).
//
// Send-sites carrying the same shapes are additionally annotated with
// `satisfies` in: useChat, usePresence, useReactions, useActivity,
// useFileUpload, useVideoHangout, useCRDT, useYjsDoc, useWebSocket,
// GatewaySocketProvider, GatewayProvider.
// ---------------------------------------------------------------------------

// chat (useChat join/leave lifecycle + send/history, GatewaySocketProvider
// feature auto-join). Gateway-real verbs (hub#1497): join | leave | send |
// history — channel REQUIRED on all; history limit OPTIONAL (server default
// when omitted). `leave` was declared in EC v0.3.57 (backfill), so the full
// verified verb set is asserted here and the useChat cleanup send-site
// carries its `satisfies` annotation.
type LocalChatJoin = { service: 'chat'; action: 'join'; channel: string };
type LocalChatLeave = { service: 'chat'; action: 'leave'; channel: string };
type LocalChatSend = {
  service: 'chat';
  action: 'send';
  channel: string;
  message: string;
  metadata?: Record<string, unknown>;
};
type LocalChatHistory = { service: 'chat'; action: 'history'; channel: string; limit?: number };
type _chatJoin = Assert<Equivalent<LocalChatJoin, RemoveIndex<ClientFramePayload<'client.chat.join'>>>>;
type _chatLeave = Assert<Equivalent<LocalChatLeave, RemoveIndex<ClientFramePayload<'client.chat.leave'>>>>;
type _chatSend = Assert<Equivalent<LocalChatSend, RemoveIndex<ClientFramePayload<'client.chat.send'>>>>;
type _chatHist = Assert<Equivalent<LocalChatHistory, RemoveIndex<ClientFramePayload<'client.chat.history'>>>>;
type _chatUnion = Assert<
  Extends<LocalChatJoin | LocalChatLeave | LocalChatSend | LocalChatHistory, ChatOutboundFrame>
>;

// presence (usePresence + GatewaySocketProvider feature auto-subscribe).
// Gateway-real contract (hub#1497): subscribe/unsubscribe REQUIRE channel;
// set REQUIRES status, reads { status, metadata, channels } and IGNORES a
// top-level channel (deprecated in EC; pinning uses the channels array).
type LocalPresenceSubscribe = { service: 'presence'; action: 'subscribe'; channel: string };
type LocalPresenceUnsubscribe = { service: 'presence'; action: 'unsubscribe'; channel: string };
type LocalPresenceSet = {
  service: 'presence';
  action: 'set';
  status: PresenceStatus;
  metadata: Record<string, unknown>;
  channels: string[];
};
type _presSub = Assert<Equivalent<LocalPresenceSubscribe, RemoveIndex<ClientFramePayload<'client.presence.subscribe'>>>>;
type _presUnsub = Assert<Equivalent<LocalPresenceUnsubscribe, RemoveIndex<ClientFramePayload<'client.presence.unsubscribe'>>>>;
type _presSet = Assert<Extends<LocalPresenceSet, ClientFramePayload<'client.presence.set'>>>;
// status must be REQUIRED in the EC declaration ("Status is required") —
// an EC regression back to optional status flips this assert.
type _presSetStatusRequired = Assert<
  Extends<undefined extends RemoveIndex<ClientFramePayload<'client.presence.set'>>['status'] ? true : false, false>
>;
// get / heartbeat — gateway-verified verbs declared in EC v0.3.57
// (backfill). NO hook sends them today, so they are asserted against the
// EC shapes directly (no send-site `satisfies`): get requires AT LEAST ONE
// of targetClientId/channel at runtime (either-or is not anyOf-encodable by
// EC's type generator, so both are optional in the type); heartbeat reads
// no payload fields beyond service/action.
type LocalPresenceGet = {
  service: 'presence';
  action: 'get';
  channel?: string;
  targetClientId?: string;
};
type LocalPresenceHeartbeat = { service: 'presence'; action: 'heartbeat'; channel?: string };
type _presGet = Assert<Equivalent<LocalPresenceGet, RemoveIndex<ClientFramePayload<'client.presence.get'>>>>;
type _presHeartbeat = Assert<
  Equivalent<LocalPresenceHeartbeat, RemoveIndex<ClientFramePayload<'client.presence.heartbeat'>>>
>;
type _presUnion = Assert<
  Extends<
    | LocalPresenceSubscribe
    | LocalPresenceUnsubscribe
    | LocalPresenceSet
    | LocalPresenceGet
    | LocalPresenceHeartbeat,
    PresenceOutboundFrame
  >
>;

// reaction (useReactions subscribe/unsubscribe lifecycle + react). Gateway-
// real verb (hub#1497) is 'send' — 'react' was never accepted ("Unknown
// reaction action"). The subscribe/unsubscribe lifecycle frames were
// declared in EC v0.3.57 (backfill), so the full verified verb set is
// asserted here and the useReactions send-sites carry their `satisfies`
// annotations. getAvailable is gateway-verified but sent by no hook today
// (subscribers get the emoji list in the reaction_subscribed reply), so it
// is asserted against the EC shape directly: no payload fields are read
// beyond service/action (channel ignored).
type LocalReactionSubscribe = { service: 'reaction'; action: 'subscribe'; channel: string };
type LocalReactionUnsubscribe = { service: 'reaction'; action: 'unsubscribe'; channel: string };
type LocalReactionGetAvailable = { service: 'reaction'; action: 'getAvailable'; channel?: string };
type LocalReactionSend = {
  service: 'reaction';
  action: 'send';
  channel: string;
  emoji: string;
  position?: Record<string, unknown>;
  targetId?: string;
  metadata?: Record<string, unknown>;
};
type _reactSub = Assert<
  Equivalent<LocalReactionSubscribe, RemoveIndex<ClientFramePayload<'client.reaction.subscribe'>>>
>;
type _reactUnsub = Assert<
  Equivalent<LocalReactionUnsubscribe, RemoveIndex<ClientFramePayload<'client.reaction.unsubscribe'>>>
>;
type _reactGetAvail = Assert<
  Equivalent<LocalReactionGetAvailable, RemoveIndex<ClientFramePayload<'client.reaction.getAvailable'>>>
>;
type _reactSend = Assert<Equivalent<LocalReactionSend, RemoveIndex<ClientFramePayload<'client.reaction.send'>>>>;
type _reactUnion = Assert<
  Extends<
    LocalReactionSubscribe | LocalReactionUnsubscribe | LocalReactionSend | LocalReactionGetAvailable,
    ReactionOutboundFrame
  >
>;

// activity (useActivity) — the hook sends the GATEWAY-real frames since
// 0.13.1 (hub#1492): keyed on `channelId` with history verb 'getHistory'.
// EC v0.3.56 adopted the real declarations (hub#1497), so all three frames
// — including getHistory — are asserted directly (the former
// `_actHistDiverges` pin is gone).
type LocalActivitySubscribe = { service: 'activity'; action: 'subscribe'; channel: string; channelId: string };
type LocalActivityUnsubscribe = { service: 'activity'; action: 'unsubscribe'; channel: string; channelId: string };
type LocalActivityHistory = { service: 'activity'; action: 'getHistory'; channel: string; channelId: string; limit: number };
type _actSub = Assert<Extends<LocalActivitySubscribe, ClientFramePayload<'client.activity.subscribe'>>>;
type _actUnsub = Assert<Extends<LocalActivityUnsubscribe, ClientFramePayload<'client.activity.unsubscribe'>>>;
type _actHist = Assert<Extends<LocalActivityHistory, ClientFramePayload<'client.activity.getHistory'>>>;
type _actUnion = Assert<
  Extends<LocalActivitySubscribe | LocalActivityUnsubscribe | LocalActivityHistory, ActivityOutboundFrame>
>;

// crdt (useCRDT / useYjsDoc / GatewayProvider)
type LocalCrdtSubscribe = { service: 'crdt'; action: 'subscribe'; channel: string };
type LocalCrdtUnsubscribe = { service: 'crdt'; action: 'unsubscribe'; channel: string };
type LocalCrdtUpdate = { service: 'crdt'; action: 'update'; channel: string; update: string };
// Canonical awareness frame. NOTE: GatewayProvider's send-site forwards
// `mode` as plain `string` (useAwarenessState.updateMode accepts any string);
// the canonical declaration narrows it to the union below. Narrowing the
// call-site would be a wire change (dropping non-standard modes), so the
// looseness is documented here instead of "fixed".
type LocalCrdtAwareness = {
  service: 'crdt';
  action: 'awareness';
  channel: string;
  update: string;
  mode?: 'editor' | 'reviewer' | 'reader';
  idle?: boolean;
};
type _crdtSub = Assert<Equivalent<LocalCrdtSubscribe, RemoveIndex<ClientFramePayload<'client.crdt.subscribe'>>>>;
type _crdtUnsub = Assert<Equivalent<LocalCrdtUnsubscribe, RemoveIndex<ClientFramePayload<'client.crdt.unsubscribe'>>>>;
type _crdtUpdate = Assert<Equivalent<LocalCrdtUpdate, RemoveIndex<ClientFramePayload<'client.crdt.update'>>>>;
type _crdtAwareness = Assert<Equivalent<LocalCrdtAwareness, RemoveIndex<ClientFramePayload<'client.crdt.awareness'>>>>;
type _crdtUnion = Assert<
  Extends<LocalCrdtSubscribe | LocalCrdtUnsubscribe | LocalCrdtUpdate | LocalCrdtAwareness, CrdtOutboundFrame>
>;

// fileupload (useFileUpload)
type LocalFileuploadRequest = {
  service: 'fileupload';
  action: 'request-upload';
  channel: string;
  id: string;
  filename: string;
  size: number;
  metadata?: Record<string, unknown>;
};
type LocalFileuploadComplete = { service: 'fileupload'; action: 'complete'; channel: string; id: string };
type LocalFileuploadCancel = { service: 'fileupload'; action: 'cancel'; channel: string; id: string };
type _fupReq = Assert<Equivalent<LocalFileuploadRequest, RemoveIndex<ClientFramePayload<'client.fileupload.request-upload'>>>>;
type _fupDone = Assert<Equivalent<LocalFileuploadComplete, RemoveIndex<ClientFramePayload<'client.fileupload.complete'>>>>;
type _fupCancel = Assert<Equivalent<LocalFileuploadCancel, RemoveIndex<ClientFramePayload<'client.fileupload.cancel'>>>>;
type _fupUnion = Assert<
  Extends<LocalFileuploadRequest | LocalFileuploadComplete | LocalFileuploadCancel, FileuploadOutboundFrame>
>;

// videohangout (useVideoHangout)
type LocalHangoutStart = {
  service: 'videohangout';
  action: 'start';
  channel: string;
  type?: 'hangout' | 'call';
  metadata?: Record<string, unknown>;
};
type LocalHangoutJoin = { service: 'videohangout'; action: 'join'; channel: string; sessionId: string };
type LocalHangoutLeave = { service: 'videohangout'; action: 'leave'; channel: string; sessionId: string };
type LocalHangoutEnd = { service: 'videohangout'; action: 'end'; channel: string; sessionId: string };
type LocalHangoutToggleVideo = {
  service: 'videohangout';
  action: 'toggle-video';
  channel: string;
  sessionId: string;
  videoOn: boolean;
};
type LocalHangoutToggleAudio = {
  service: 'videohangout';
  action: 'toggle-audio';
  channel: string;
  sessionId: string;
  audioOn: boolean;
};
type _vhStart = Assert<Equivalent<LocalHangoutStart, RemoveIndex<ClientFramePayload<'client.videohangout.start'>>>>;
type _vhJoin = Assert<Equivalent<LocalHangoutJoin, RemoveIndex<ClientFramePayload<'client.videohangout.join'>>>>;
type _vhLeave = Assert<Equivalent<LocalHangoutLeave, RemoveIndex<ClientFramePayload<'client.videohangout.leave'>>>>;
type _vhEnd = Assert<Equivalent<LocalHangoutEnd, RemoveIndex<ClientFramePayload<'client.videohangout.end'>>>>;
type _vhTv = Assert<Equivalent<LocalHangoutToggleVideo, RemoveIndex<ClientFramePayload<'client.videohangout.toggle-video'>>>>;
type _vhTa = Assert<Equivalent<LocalHangoutToggleAudio, RemoveIndex<ClientFramePayload<'client.videohangout.toggle-audio'>>>>;
type _vhUnion = Assert<
  Extends<
    | LocalHangoutStart
    | LocalHangoutJoin
    | LocalHangoutLeave
    | LocalHangoutEnd
    | LocalHangoutToggleVideo
    | LocalHangoutToggleAudio,
    VideohangoutOutboundFrame
  >
>;

// subscribe multiplexer (useWebSocket subscribe/unsubscribe + auto-resubscribe)
type LocalGenericSubscribe = { service: 'subscribe'; action: 'subscribe'; channel: string };
type LocalGenericUnsubscribe = { service: 'subscribe'; action: 'unsubscribe'; channel: string };
type _genSub = Assert<Equivalent<LocalGenericSubscribe, RemoveIndex<ClientFramePayload<'client.subscribe.subscribe'>>>>;
type _genUnsub = Assert<Equivalent<LocalGenericUnsubscribe, RemoveIndex<ClientFramePayload<'client.subscribe.unsubscribe'>>>>;
type _genUnion = Assert<Extends<LocalGenericSubscribe | LocalGenericUnsubscribe, SubscribeOutboundFrame>>;

// ---------------------------------------------------------------------------
// 3. Inbound hook-contract frames — the 12 ws.* declarations EC added for
// the hook contracts (presence:joined/left, fileupload:*, videohangout:*,
// notification:*, capability/feature-flag updated).
// ---------------------------------------------------------------------------

// presence:joined → PresenceEntry (usePresence roster entries).
// EC `client` is pre-parse (only clientId required, status is plain string);
// PresenceEntry is post-parse (asPresenceEntry fills defaults, status is the
// documented PresenceStatus vocabulary). Assert key parity + local→EC.
type EcPresenceJoinedClient = RemoveIndex<EventPayloadMap['ws.presence.joined']['client']>;
type _presenceEntryKeys = Assert<SameKeys<PresenceEntry, EcPresenceJoinedClient>>;
type _presenceEntryFields = Assert<Extends<PresenceEntry, EcPresenceJoinedClient>>;
type _presenceStatusIsString = Assert<Extends<PresenceStatus, EcPresenceJoinedClient['status']>>;

// presence:left → { channel, clientId } (usePresence removal path).
type EcPresenceLeft = EventPayloadMap['ws.presence.left'];
type _presenceLeft = Assert<Extends<{ type: 'presence:left'; channel: string; clientId: string }, EcPresenceLeft>>;

// fileupload:progress / scanning / cancelled → fields useFileUpload reads.
type EcFupProgress = EventPayloadMap['ws.fileupload.progress'];
type _fupProgId = Assert<Extends<EcFupProgress['id'], string>>;
type _fupProgPct = Assert<Extends<EcFupProgress['progress'], FileUploadState['progress'] & number>>;
type _fupScanning = Assert<Extends<EventPayloadMap['ws.fileupload.scanning']['id'], string>>;
type _fupCancelled = Assert<Extends<EventPayloadMap['ws.fileupload.cancelled']['id'], string>>;

// videohangout:participant → HangoutParticipant.
// Same pre/post-parse split: EC marks videoOn/audioOn/joinedAt optional on
// the wire; asParticipant() defaults them, so they are required locally.
type EcHangoutParticipant = RemoveIndex<EventPayloadMap['ws.videohangout.participant']['participant']>;
type _participantKeys = Assert<SameKeys<HangoutParticipant, EcHangoutParticipant>>;
type _participantFields = Assert<Extends<HangoutParticipant, EcHangoutParticipant>>;
type _participantRole = Assert<Equivalent<HangoutParticipant['role'], EcHangoutParticipant['role']>>;

// videohangout:media → media-toggle fanout fields.
type EcHangoutMedia = EventPayloadMap['ws.videohangout.media'];
type _media = Assert<
  Extends<
    { type: 'videohangout:media'; channel: string; clientId: string; videoOn: boolean; audioOn: boolean },
    EcHangoutMedia
  >
>;

// notification:new / read / bulk-update → Notification (useNotifications).
type EcNotificationPayload = RemoveIndex<EventPayloadMap['ws.notification.new']['payload']>;
type _notificationKeys = Assert<SameKeys<Notification, EcNotificationPayload>>;
type _notificationFields = Assert<Extends<Notification, EcNotificationPayload>>;
type _notificationRead = Assert<Extends<EventPayloadMap['ws.notification.read']['payload']['id'], string>>;
type EcBulkNotification = RemoveIndex<
  EventPayloadMap['ws.notification.bulk-update']['payload']['notifications'][number]
>;
type _notificationBulk = Assert<Extends<Notification, EcBulkNotification>>;

// capability:updated → CapabilityDescriptor (useCapability).
type EcCapabilityPayload = RemoveIndex<EventPayloadMap['ws.capability.updated']['payload']>;
type _capabilityKeys = Assert<SameKeys<CapabilityDescriptor, EcCapabilityPayload>>;
type _capability = Assert<Equivalent<CapabilityDescriptor, EcCapabilityPayload>>;

// feature-flag:updated → useFeatureFlag's (module-private) payload mirror.
type LocalFeatureFlagPayload = {
  name: string;
  enabled: boolean;
  variant?: string;
  metadata?: Record<string, unknown>;
};
type _featureFlag = Assert<Equivalent<LocalFeatureFlagPayload, RemoveIndex<EventPayloadMap['ws.feature-flag.updated']['payload']>>>;

// ---------------------------------------------------------------------------
// 3b. Gateway SEND-BACK envelopes — the action-frame envelopes useChat /
// usePresence / useReactions PARSE (divergence note b, RESOLVED by EC 0.3.58).
//
// EC 0.3.58 declared the complete gateway send-back set per the service
// implementations the gateway runs (websocket-gateway/node_modules/
// @connorhoehn/realtime-modules/dist/{chat,presence,reactions,crdt}/). The
// hooks parse these envelopes payload-first; below we assert that the envelope
// LITERALS the hooks branch on (msg.type === 'chat' && msg.action ===
// 'message', etc.) match the EC declarations, and that the per-frame payload
// slot the hook extracts (message / presence / data) accepts the local
// post-parse type (ChatMessage / PresenceEntry / Reaction). The EC payloads
// model the PRE-PARSE wire (the inner object is Record<string, unknown>, so
// the as*() guards' POST-PARSE local types are assignable into it).

// The hooks' public payload types are interfaces (no index signature), so they
// are NOT whole-object assignable into the EC pre-parse slots (which are loose
// Record<string, unknown>). Following the §3 pattern, each frame is asserted in
// two parts: (1) the ENVELOPE discriminants (type/action + key fields) the hook
// branches on match the EC declaration; (2) the local payload type the as*()
// guard produces is a valid object for the EC slot, checked field-wise via the
// existing _activityFields / _notificationFields / _reactionCore style.

// chat — { type:'chat', action:'message', message } / { ..., action:'history',
// messages } (useChat gateway-real branch).
type EcChatMessageEnvelope = EventPayloadMap['ws.chat.message'];
type EcChatHistoryEnvelope = EventPayloadMap['ws.chat.history'];
type _chatMsgType = Assert<Equivalent<EcChatMessageEnvelope['type'], 'chat'>>;
type _chatMsgAction = Assert<Equivalent<EcChatMessageEnvelope['action'], 'message'>>;
type _chatMsgChannel = Assert<Extends<EcChatMessageEnvelope['channel'], string>>;
type _chatMsgSlot = Assert<Extends<ChatMessage, RemoveIndex<EcChatMessageEnvelope['message']>>>;
type _chatHistType = Assert<Equivalent<EcChatHistoryEnvelope['action'], 'history'>>;
type _chatHistSlot = Assert<Extends<ChatMessage, RemoveIndex<EcChatHistoryEnvelope['messages'][number]>>>;

// presence — { type:'presence', action:'subscribed', presence: PresenceEntry[] }
// / { action:'set'|'update', presence: PresenceEntry } (usePresence gateway-real
// branch). presence is optional on the wire (server may omit); assert the slot
// accepts PresenceEntry once present.
type EcPresenceSubscribedEnvelope = EventPayloadMap['ws.presence.subscribed'];
type EcPresenceSetEnvelope = EventPayloadMap['ws.presence.set'];
type EcPresenceUpdateEnvelope = EventPayloadMap['ws.presence.update'];
type _presSubAction = Assert<Equivalent<EcPresenceSubscribedEnvelope['action'], 'subscribed'>>;
type _presSubChannel = Assert<Extends<EcPresenceSubscribedEnvelope['channel'], string>>;
type _presSubSlot = Assert<
  Extends<PresenceEntry, RemoveIndex<NonNullable<EcPresenceSubscribedEnvelope['presence']>[number]>>
>;
type _presSetAction = Assert<Equivalent<EcPresenceSetEnvelope['action'], 'set'>>;
type _presSetSlot = Assert<Extends<PresenceEntry, RemoveIndex<NonNullable<EcPresenceSetEnvelope['presence']>>>>;
type _presUpdateAction = Assert<Equivalent<EcPresenceUpdateEnvelope['action'], 'update'>>;
type _presUpdateSlot = Assert<Extends<PresenceEntry, RemoveIndex<NonNullable<EcPresenceUpdateEnvelope['presence']>>>>;

// reaction — { type:'reaction', action:'reaction_received', data: Reaction }
// (useReactions gateway-real branch). The data slot accepts the local Reaction
// post-parse type; the ack envelopes (reaction_unsubscribed / available_reactions
// — newly declared in 0.3.58) are pinned so the "no state change needed" branch
// stays contract-covered.
type EcReactionReceivedEnvelope = EventPayloadMap['ws.reaction.received'];
type _reactReceivedType = Assert<Equivalent<EcReactionReceivedEnvelope['type'], 'reaction'>>;
type _reactReceivedAction = Assert<Equivalent<EcReactionReceivedEnvelope['action'], 'reaction_received'>>;
type _reactReceivedSlot = Assert<Extends<Reaction, RemoveIndex<EcReactionReceivedEnvelope['data']>>>;
type _reactUnsubAck = Assert<
  Extends<EventPayloadMap['ws.reaction.unsubscribed']['action'], 'reaction_unsubscribed'>
>;
type _reactAvailableAck = Assert<
  Extends<EventPayloadMap['ws.reaction.available']['data']['reactions'], Record<string, unknown>>
>;
type _reactSentAck = Assert<
  Extends<EventPayloadMap['ws.reaction.sent']['data']['reactionId'], string>
>;

// crdt — { type:'crdt:awareness', channel, updates:[{ clientId, update }] }
// (newly declared in 0.3.58; the dist AwarenessCoalescer emit shape, distinct
// from the historical ws.crdt.awareness-batch). Pin the envelope literal +
// per-entry fields.
type EcCrdtAwarenessEnvelope = EventPayloadMap['ws.crdt.awareness'];
type EcCrdtAwarenessEntry = RemoveIndex<EcCrdtAwarenessEnvelope['updates'][number]>;
type _crdtAwarenessType = Assert<Equivalent<EcCrdtAwarenessEnvelope['type'], 'crdt:awareness'>>;
type _crdtAwarenessChannel = Assert<Extends<EcCrdtAwarenessEnvelope['channel'], string>>;
type _crdtAwarenessEntry = Assert<
  Extends<{ clientId: string; update: string }, EcCrdtAwarenessEntry>
>;

// ---------------------------------------------------------------------------
// 4. Known divergences (documented, deliberately NOT "fixed" in Wave A3 —
// each fix would be a runtime behavior change, not a doc/type correction).
//
// a) useActivity inbound envelope — RESOLVED in 0.13.1 (hub#1492). The hook
//    now parses the gateway-real envelopes
//      { type: 'activity:event', payload: { eventType, detail, ... } }
//      { type: 'activity', action: 'history', events, channelId }
//    payload-first, with the old flat shapes
//      { type: 'activity:event', channel, ...ActivityEvent }
//      { type: 'activity:history', channel, events: [...] }
//    kept as a legacy fallback. Live activity:event frames carry NO channel
//    field (single global 'activity:broadcast' channel; the gateway scopes
//    delivery via the channel subscription), so the hook accepts every
//    activity:event on the socket and only channel-filters legacy flat
//    frames + history responses (channelId).
//
// b) RESOLVED in EC v0.3.58 (2026-06-12). useChat / useReactions /
//    usePresence parse the gateway-real action-frame envelopes
//    ({ type: 'chat', action: 'message'|'history' }, { type: 'reaction',
//    action: 'reaction_received', data }, { type: 'presence', action:
//    'subscribed'|'set'|'update'|'offline' }) payload-first, with the old
//    flat shapes (chat:message / chat:history / reaction:new /
//    reaction:history / presence:state / presence:joined / presence:updated
//    / presence:left) kept as a legacy fallback. EC 0.3.58 declared the
//    COMPLETE gateway send-back set per the service implementations the
//    gateway runs (dist/{chat,presence,reactions,crdt}/) — including the
//    previously-missing reaction/reaction_unsubscribed, available_reactions
//    and crdt:awareness frames, and reconciled reaction_subscribed/sent +
//    ws.error against ground truth. §3b above now asserts the hooks' parsers
//    against the full inbound-envelope set directly (the former
//    "assertions remain TODO" caveat is gone).
//
// c) RESOLVED in EC v0.3.57 (backfill): chat/leave (useChat cleanup) and
//    reaction/subscribe + reaction/unsubscribe (useReactions lifecycle) are
//    now declared; their send-sites carry `satisfies` annotations like
//    their siblings, and §2 asserts them directly. EC also backfilled the
//    hook-less gateway-verified verbs reaction/getAvailable +
//    presence/get + presence/heartbeat (asserted in §2 against the EC
//    shapes; no send-site exists to annotate).
//
// d) RESOLVED in EC v0.3.56 (hub#1497): client.activity.* now declares the
//    gateway-real `channelId` + 'getHistory' frames; the former
//    `_actHistDiverges` pin in §2 was replaced by the direct `_actHist`
//    assertion and useActivity.loadHistory regained its `satisfies`
//    annotation.
// ---------------------------------------------------------------------------

// ActivityEvent field shape vs EC's ws.activity.event payload (post-parse →
// pre-parse direction + key parity), envelope divergence notwithstanding.
type EcActivityEventPayload = RemoveIndex<EventPayloadMap['ws.activity.event']['payload']>;
type _activityKeys = Assert<SameKeys<ActivityEvent, EcActivityEventPayload>>;
type _activityFields = Assert<Extends<ActivityEvent, EcActivityEventPayload>>;

// Reaction core wire fields vs the ws.reaction.received data block. The full
// received-envelope assertion now lives in §3b (_reactReceivedEnvelope); this
// field-level check is retained as the post-parse → pre-parse data-slot pin.
type EcReactionData = RemoveIndex<EventPayloadMap['ws.reaction.received']['data']>;
type _reactionCore = Assert<Extends<Reaction, EcReactionData>>;

// ChatMessage is now asserted against the ws.chat.message / ws.chat.history
// envelope payload slots in §3b; this id-level pin keeps the import
// load-bearing if the type is renamed.
type _chatMessageStillExported = Assert<Extends<ChatMessage['id'], string>>;

// ---------------------------------------------------------------------------
// Runtime stub — keeps jest happy; the real assertions are the types above.
// A representative frame per service exercises that the EC types describe
// constructible values (and that the type-only imports erased at runtime).
// ---------------------------------------------------------------------------

describe('contract conformance (compile-time)', () => {
  it('EC client-frame payloads are constructible from hook frame shapes', () => {
    const chatSend: ClientFramePayload<'client.chat.send'> = {
      service: 'chat',
      action: 'send',
      channel: 'chat:general',
      message: 'hello',
    };
    const reactionSend: ClientFramePayload<'client.reaction.send'> = {
      service: 'reaction',
      action: 'send',
      channel: 'chat:general',
      emoji: '🔥',
    };
    const resub: ClientFramePayload<'client.subscribe.subscribe'> = {
      service: 'subscribe',
      action: 'subscribe',
      channel: 'doc:readme',
    };
    expect(chatSend.service).toBe('chat');
    expect(reactionSend.action).toBe('send');
    expect(resub.channel).toBe('doc:readme');
  });

  it('type-only event-catalog imports leave no runtime require', () => {
    // If the import at the top of this file were not type-only, jest's
    // module registry would contain the EC package after loading this file.
    const ecRuntime = Object.keys(require.cache).filter((k) =>
      k.includes(`${'@connorhoehn'}/event-catalog`),
    );
    expect(ecRuntime).toEqual([]);
  });
});
