// test/contract/contract-conformance.test.ts
//
// Wave A3 contract drift guard.
//
// Asserts — at COMPILE TIME — that this library's public types and the
// frames its hooks send/parse stay conformant with the canonical client-
// frame declarations generated by @connorhoehn/event-catalog (v0.3.56+,
// `client-frames` subpath: 25 outbound `client.<service>.<action>` frames
// + the inbound `ws.*` hook-contract declarations). EC v0.3.56 corrected
// the chat/presence/reaction/activity declarations against gateway service
// ground truth (hub#1497): chat verb is 'join' (not 'subscribe'), reaction
// verb is 'send' (not 'react'), presence.subscribe requires channel,
// presence.set requires status (channel deprecated; pinning via channels[]),
// chat.history limit optional, activity keyed on channelId with verb
// 'getHistory'.
//
// How it runs:
//   - `npm run check:contract` — standalone tsc pass (tsconfig.contract.json).
//   - `npm test` — ts-jest type-checks this file on every suite run, so any
//     drift between the local types and the EC-generated unions fails CI-less
//     local runs too. The runtime `describe` block below is intentionally
//     trivial; the assertions are the types.
//
// Design notes:
//   - The library's public types in src/client/types.ts are deliberately NOT
//     aliased to EC types: event-catalog is a devDependency only, and the
//     built dist (.js and .d.ts) must stay free of event-catalog references
//     so consumers of the prebuilt dist need no new dependency. Conformance
//     is therefore asserted here instead of by aliasing.
//   - Outbound frames also carry inline `satisfies ClientFramePayload<...>`
//     annotations at every hook send-site, so send-site drift fails the main
//     build as well. This file additionally pins the FULL outbound frame-name
//     set, so a frame ADDED to (or removed from) event-catalog fails here and
//     forces an explicit decision in this library.
//   - EC inbound payloads model the PRE-PARSE wire (fields the gateway may
//     omit are optional); the local public types are POST-PARSE (the hooks'
//     as*() guards fill defaults, so fields are required). Full mutual
//     assignability is therefore asserted field-wise + by key-set parity,
//     not by whole-object assignability in the EC→local direction.

import type {
  ClientFramePayloadMap,
  ClientFramePayload,
  ChatOutboundFrame,
  PresenceOutboundFrame,
  ReactionOutboundFrame,
  ActivityOutboundFrame,
  CrdtOutboundFrame,
  FileuploadOutboundFrame,
  VideohangoutOutboundFrame,
  SubscribeOutboundFrame,
} from '@connorhoehn/event-catalog/client-frames';
import type { EventPayloadMap } from '@connorhoehn/event-catalog/types';

import type {
  ChatMessage,
  PresenceEntry,
  PresenceStatus,
  Reaction,
  ActivityEvent,
} from '../../src/client/types';
import type { HangoutParticipant } from '../../src/client/useVideoHangout';
import type { Notification } from '../../src/client/useNotifications';
import type { CapabilityDescriptor } from '../../src/client/useCapability';
import type { FileUploadState } from '../../src/client/useFileUpload';

// ---------------------------------------------------------------------------
// Assertion helpers
// ---------------------------------------------------------------------------

type Assert<T extends true> = T;
type Extends<A, B> = [A] extends [B] ? true : false;
/** Mutual assignability. */
type Equivalent<A, B> = Extends<A, B> extends true ? Extends<B, A> : false;
/** Strip string/number index signatures so declared keys can be compared. */
type RemoveIndex<T> = {
  [K in keyof T as string extends K ? never : number extends K ? never : K]: T[K];
};
/** Exact key-set parity between two object types. */
type SameKeys<A, B> = Equivalent<keyof A, keyof B>;

// ---------------------------------------------------------------------------
// 1. Outbound frame-name coverage — pins the full ClientFramePayloadMap.
//
// If event-catalog ADDS an outbound client frame, `_outboundNamesPinned`
// fails until this library either implements the frame or consciously lists
// it here. If EC REMOVES/renames one, the per-frame assertions below fail.
// ---------------------------------------------------------------------------

type ExpectedOutboundFrameName =
  | 'client.chat.join'
  | 'client.chat.send'
  | 'client.chat.history'
  | 'client.presence.subscribe'
  | 'client.presence.unsubscribe'
  | 'client.presence.set'
  | 'client.reaction.send'
  | 'client.activity.subscribe'
  | 'client.activity.unsubscribe'
  | 'client.activity.getHistory'
  | 'client.crdt.subscribe'
  | 'client.crdt.unsubscribe'
  | 'client.crdt.update'
  | 'client.crdt.awareness'
  | 'client.fileupload.request-upload'
  | 'client.fileupload.complete'
  | 'client.fileupload.cancel'
  | 'client.videohangout.start'
  | 'client.videohangout.join'
  | 'client.videohangout.leave'
  | 'client.videohangout.end'
  | 'client.videohangout.toggle-video'
  | 'client.videohangout.toggle-audio'
  | 'client.subscribe.subscribe'
  | 'client.subscribe.unsubscribe';

type _outboundNamesPinned = Assert<
  Equivalent<keyof ClientFramePayloadMap, ExpectedOutboundFrameName>
>;

// ---------------------------------------------------------------------------
// 2. Outbound frames — representative shapes of what each hook actually
// sends, asserted MUTUALLY assignable with the EC payload (the EC payloads
// carry `[key: string]: unknown`, so the reverse direction holds whenever
// the declared fields agree).
//
// Send-sites carrying the same shapes are additionally annotated with
// `satisfies` in: useChat, usePresence, useReactions, useActivity,
// useFileUpload, useVideoHangout, useCRDT, useYjsDoc, useWebSocket,
// GatewaySocketProvider, GatewayProvider.
// ---------------------------------------------------------------------------

// chat (useChat join/leave lifecycle + send/history, GatewaySocketProvider
// feature auto-join). Gateway-real verbs (hub#1497): join | leave | send |
// history — channel REQUIRED on all; history limit OPTIONAL (server default
// when omitted). `leave` is gateway-verified but has no EC declaration yet,
// so only join/send/history are asserted here.
type LocalChatJoin = { service: 'chat'; action: 'join'; channel: string };
type LocalChatSend = {
  service: 'chat';
  action: 'send';
  channel: string;
  message: string;
  metadata?: Record<string, unknown>;
};
type LocalChatHistory = { service: 'chat'; action: 'history'; channel: string; limit?: number };
type _chatJoin = Assert<Equivalent<LocalChatJoin, RemoveIndex<ClientFramePayload<'client.chat.join'>>>>;
type _chatSend = Assert<Equivalent<LocalChatSend, RemoveIndex<ClientFramePayload<'client.chat.send'>>>>;
type _chatHist = Assert<Equivalent<LocalChatHistory, RemoveIndex<ClientFramePayload<'client.chat.history'>>>>;
type _chatUnion = Assert<Extends<LocalChatJoin | LocalChatSend | LocalChatHistory, ChatOutboundFrame>>;

// presence (usePresence + GatewaySocketProvider feature auto-subscribe).
// Gateway-real contract (hub#1497): subscribe/unsubscribe REQUIRE channel;
// set REQUIRES status, reads { status, metadata, channels } and IGNORES a
// top-level channel (deprecated in EC; pinning uses the channels array).
type LocalPresenceSubscribe = { service: 'presence'; action: 'subscribe'; channel: string };
type LocalPresenceUnsubscribe = { service: 'presence'; action: 'unsubscribe'; channel: string };
type LocalPresenceSet = {
  service: 'presence';
  action: 'set';
  status: PresenceStatus;
  metadata: Record<string, unknown>;
  channels: string[];
};
type _presSub = Assert<Equivalent<LocalPresenceSubscribe, RemoveIndex<ClientFramePayload<'client.presence.subscribe'>>>>;
type _presUnsub = Assert<Equivalent<LocalPresenceUnsubscribe, RemoveIndex<ClientFramePayload<'client.presence.unsubscribe'>>>>;
type _presSet = Assert<Extends<LocalPresenceSet, ClientFramePayload<'client.presence.set'>>>;
// status must be REQUIRED in the EC declaration ("Status is required") —
// an EC regression back to optional status flips this assert.
type _presSetStatusRequired = Assert<
  Extends<undefined extends RemoveIndex<ClientFramePayload<'client.presence.set'>>['status'] ? true : false, false>
>;
type _presUnion = Assert<
  Extends<LocalPresenceSubscribe | LocalPresenceUnsubscribe | LocalPresenceSet, PresenceOutboundFrame>
>;

// reaction (useReactions.react). Gateway-real verb (hub#1497) is 'send' —
// 'react' was never accepted ("Unknown reaction action"). The hook's
// subscribe/unsubscribe lifecycle frames are gateway-verified but have no
// EC declarations yet, so only the send frame is asserted here.
type LocalReactionSend = {
  service: 'reaction';
  action: 'send';
  channel: string;
  emoji: string;
  position?: Record<string, unknown>;
  targetId?: string;
  metadata?: Record<string, unknown>;
};
type _reactSend = Assert<Equivalent<LocalReactionSend, RemoveIndex<ClientFramePayload<'client.reaction.send'>>>>;
type _reactUnion = Assert<Extends<LocalReactionSend, ReactionOutboundFrame>>;

// activity (useActivity) — the hook sends the GATEWAY-real frames since
// 0.13.1 (hub#1492): keyed on `channelId` with history verb 'getHistory'.
// EC v0.3.56 adopted the real declarations (hub#1497), so all three frames
// — including getHistory — are asserted directly (the former
// `_actHistDiverges` pin is gone).
type LocalActivitySubscribe = { service: 'activity'; action: 'subscribe'; channel: string; channelId: string };
type LocalActivityUnsubscribe = { service: 'activity'; action: 'unsubscribe'; channel: string; channelId: string };
type LocalActivityHistory = { service: 'activity'; action: 'getHistory'; channel: string; channelId: string; limit: number };
type _actSub = Assert<Extends<LocalActivitySubscribe, ClientFramePayload<'client.activity.subscribe'>>>;
type _actUnsub = Assert<Extends<LocalActivityUnsubscribe, ClientFramePayload<'client.activity.unsubscribe'>>>;
type _actHist = Assert<Extends<LocalActivityHistory, ClientFramePayload<'client.activity.getHistory'>>>;
type _actUnion = Assert<
  Extends<LocalActivitySubscribe | LocalActivityUnsubscribe | LocalActivityHistory, ActivityOutboundFrame>
>;

// crdt (useCRDT / useYjsDoc / GatewayProvider)
type LocalCrdtSubscribe = { service: 'crdt'; action: 'subscribe'; channel: string };
type LocalCrdtUnsubscribe = { service: 'crdt'; action: 'unsubscribe'; channel: string };
type LocalCrdtUpdate = { service: 'crdt'; action: 'update'; channel: string; update: string };
// Canonical awareness frame. NOTE: GatewayProvider's send-site forwards
// `mode` as plain `string` (useAwarenessState.updateMode accepts any string);
// the canonical declaration narrows it to the union below. Narrowing the
// call-site would be a wire change (dropping non-standard modes), so the
// looseness is documented here instead of "fixed".
type LocalCrdtAwareness = {
  service: 'crdt';
  action: 'awareness';
  channel: string;
  update: string;
  mode?: 'editor' | 'reviewer' | 'reader';
  idle?: boolean;
};
type _crdtSub = Assert<Equivalent<LocalCrdtSubscribe, RemoveIndex<ClientFramePayload<'client.crdt.subscribe'>>>>;
type _crdtUnsub = Assert<Equivalent<LocalCrdtUnsubscribe, RemoveIndex<ClientFramePayload<'client.crdt.unsubscribe'>>>>;
type _crdtUpdate = Assert<Equivalent<LocalCrdtUpdate, RemoveIndex<ClientFramePayload<'client.crdt.update'>>>>;
type _crdtAwareness = Assert<Equivalent<LocalCrdtAwareness, RemoveIndex<ClientFramePayload<'client.crdt.awareness'>>>>;
type _crdtUnion = Assert<
  Extends<LocalCrdtSubscribe | LocalCrdtUnsubscribe | LocalCrdtUpdate | LocalCrdtAwareness, CrdtOutboundFrame>
>;

// fileupload (useFileUpload)
type LocalFileuploadRequest = {
  service: 'fileupload';
  action: 'request-upload';
  channel: string;
  id: string;
  filename: string;
  size: number;
  metadata?: Record<string, unknown>;
};
type LocalFileuploadComplete = { service: 'fileupload'; action: 'complete'; channel: string; id: string };
type LocalFileuploadCancel = { service: 'fileupload'; action: 'cancel'; channel: string; id: string };
type _fupReq = Assert<Equivalent<LocalFileuploadRequest, RemoveIndex<ClientFramePayload<'client.fileupload.request-upload'>>>>;
type _fupDone = Assert<Equivalent<LocalFileuploadComplete, RemoveIndex<ClientFramePayload<'client.fileupload.complete'>>>>;
type _fupCancel = Assert<Equivalent<LocalFileuploadCancel, RemoveIndex<ClientFramePayload<'client.fileupload.cancel'>>>>;
type _fupUnion = Assert<
  Extends<LocalFileuploadRequest | LocalFileuploadComplete | LocalFileuploadCancel, FileuploadOutboundFrame>
>;

// videohangout (useVideoHangout)
type LocalHangoutStart = {
  service: 'videohangout';
  action: 'start';
  channel: string;
  type?: 'hangout' | 'call';
  metadata?: Record<string, unknown>;
};
type LocalHangoutJoin = { service: 'videohangout'; action: 'join'; channel: string; sessionId: string };
type LocalHangoutLeave = { service: 'videohangout'; action: 'leave'; channel: string; sessionId: string };
type LocalHangoutEnd = { service: 'videohangout'; action: 'end'; channel: string; sessionId: string };
type LocalHangoutToggleVideo = {
  service: 'videohangout';
  action: 'toggle-video';
  channel: string;
  sessionId: string;
  videoOn: boolean;
};
type LocalHangoutToggleAudio = {
  service: 'videohangout';
  action: 'toggle-audio';
  channel: string;
  sessionId: string;
  audioOn: boolean;
};
type _vhStart = Assert<Equivalent<LocalHangoutStart, RemoveIndex<ClientFramePayload<'client.videohangout.start'>>>>;
type _vhJoin = Assert<Equivalent<LocalHangoutJoin, RemoveIndex<ClientFramePayload<'client.videohangout.join'>>>>;
type _vhLeave = Assert<Equivalent<LocalHangoutLeave, RemoveIndex<ClientFramePayload<'client.videohangout.leave'>>>>;
type _vhEnd = Assert<Equivalent<LocalHangoutEnd, RemoveIndex<ClientFramePayload<'client.videohangout.end'>>>>;
type _vhTv = Assert<Equivalent<LocalHangoutToggleVideo, RemoveIndex<ClientFramePayload<'client.videohangout.toggle-video'>>>>;
type _vhTa = Assert<Equivalent<LocalHangoutToggleAudio, RemoveIndex<ClientFramePayload<'client.videohangout.toggle-audio'>>>>;
type _vhUnion = Assert<
  Extends<
    | LocalHangoutStart
    | LocalHangoutJoin
    | LocalHangoutLeave
    | LocalHangoutEnd
    | LocalHangoutToggleVideo
    | LocalHangoutToggleAudio,
    VideohangoutOutboundFrame
  >
>;

// subscribe multiplexer (useWebSocket subscribe/unsubscribe + auto-resubscribe)
type LocalGenericSubscribe = { service: 'subscribe'; action: 'subscribe'; channel: string };
type LocalGenericUnsubscribe = { service: 'subscribe'; action: 'unsubscribe'; channel: string };
type _genSub = Assert<Equivalent<LocalGenericSubscribe, RemoveIndex<ClientFramePayload<'client.subscribe.subscribe'>>>>;
type _genUnsub = Assert<Equivalent<LocalGenericUnsubscribe, RemoveIndex<ClientFramePayload<'client.subscribe.unsubscribe'>>>>;
type _genUnion = Assert<Extends<LocalGenericSubscribe | LocalGenericUnsubscribe, SubscribeOutboundFrame>>;

// ---------------------------------------------------------------------------
// 3. Inbound hook-contract frames — the 12 ws.* declarations EC added for
// the hook contracts (presence:joined/left, fileupload:*, videohangout:*,
// notification:*, capability/feature-flag updated).
// ---------------------------------------------------------------------------

// presence:joined → PresenceEntry (usePresence roster entries).
// EC `client` is pre-parse (only clientId required, status is plain string);
// PresenceEntry is post-parse (asPresenceEntry fills defaults, status is the
// documented PresenceStatus vocabulary). Assert key parity + local→EC.
type EcPresenceJoinedClient = RemoveIndex<EventPayloadMap['ws.presence.joined']['client']>;
type _presenceEntryKeys = Assert<SameKeys<PresenceEntry, EcPresenceJoinedClient>>;
type _presenceEntryFields = Assert<Extends<PresenceEntry, EcPresenceJoinedClient>>;
type _presenceStatusIsString = Assert<Extends<PresenceStatus, EcPresenceJoinedClient['status']>>;

// presence:left → { channel, clientId } (usePresence removal path).
type EcPresenceLeft = EventPayloadMap['ws.presence.left'];
type _presenceLeft = Assert<Extends<{ type: 'presence:left'; channel: string; clientId: string }, EcPresenceLeft>>;

// fileupload:progress / scanning / cancelled → fields useFileUpload reads.
type EcFupProgress = EventPayloadMap['ws.fileupload.progress'];
type _fupProgId = Assert<Extends<EcFupProgress['id'], string>>;
type _fupProgPct = Assert<Extends<EcFupProgress['progress'], FileUploadState['progress'] & number>>;
type _fupScanning = Assert<Extends<EventPayloadMap['ws.fileupload.scanning']['id'], string>>;
type _fupCancelled = Assert<Extends<EventPayloadMap['ws.fileupload.cancelled']['id'], string>>;

// videohangout:participant → HangoutParticipant.
// Same pre/post-parse split: EC marks videoOn/audioOn/joinedAt optional on
// the wire; asParticipant() defaults them, so they are required locally.
type EcHangoutParticipant = RemoveIndex<EventPayloadMap['ws.videohangout.participant']['participant']>;
type _participantKeys = Assert<SameKeys<HangoutParticipant, EcHangoutParticipant>>;
type _participantFields = Assert<Extends<HangoutParticipant, EcHangoutParticipant>>;
type _participantRole = Assert<Equivalent<HangoutParticipant['role'], EcHangoutParticipant['role']>>;

// videohangout:media → media-toggle fanout fields.
type EcHangoutMedia = EventPayloadMap['ws.videohangout.media'];
type _media = Assert<
  Extends<
    { type: 'videohangout:media'; channel: string; clientId: string; videoOn: boolean; audioOn: boolean },
    EcHangoutMedia
  >
>;

// notification:new / read / bulk-update → Notification (useNotifications).
type EcNotificationPayload = RemoveIndex<EventPayloadMap['ws.notification.new']['payload']>;
type _notificationKeys = Assert<SameKeys<Notification, EcNotificationPayload>>;
type _notificationFields = Assert<Extends<Notification, EcNotificationPayload>>;
type _notificationRead = Assert<Extends<EventPayloadMap['ws.notification.read']['payload']['id'], string>>;
type EcBulkNotification = RemoveIndex<
  EventPayloadMap['ws.notification.bulk-update']['payload']['notifications'][number]
>;
type _notificationBulk = Assert<Extends<Notification, EcBulkNotification>>;

// capability:updated → CapabilityDescriptor (useCapability).
type EcCapabilityPayload = RemoveIndex<EventPayloadMap['ws.capability.updated']['payload']>;
type _capabilityKeys = Assert<SameKeys<CapabilityDescriptor, EcCapabilityPayload>>;
type _capability = Assert<Equivalent<CapabilityDescriptor, EcCapabilityPayload>>;

// feature-flag:updated → useFeatureFlag's (module-private) payload mirror.
type LocalFeatureFlagPayload = {
  name: string;
  enabled: boolean;
  variant?: string;
  metadata?: Record<string, unknown>;
};
type _featureFlag = Assert<Equivalent<LocalFeatureFlagPayload, RemoveIndex<EventPayloadMap['ws.feature-flag.updated']['payload']>>>;

// ---------------------------------------------------------------------------
// 4. Known divergences (documented, deliberately NOT "fixed" in Wave A3 —
// each fix would be a runtime behavior change, not a doc/type correction).
//
// a) useActivity inbound envelope — RESOLVED in 0.13.1 (hub#1492). The hook
//    now parses the gateway-real envelopes
//      { type: 'activity:event', payload: { eventType, detail, ... } }
//      { type: 'activity', action: 'history', events, channelId }
//    payload-first, with the old flat shapes
//      { type: 'activity:event', channel, ...ActivityEvent }
//      { type: 'activity:history', channel, events: [...] }
//    kept as a legacy fallback. Live activity:event frames carry NO channel
//    field (single global 'activity:broadcast' channel; the gateway scopes
//    delivery via the channel subscription), so the hook accepts every
//    activity:event on the socket and only channel-filters legacy flat
//    frames + history responses (channelId).
//
// b) useChat / useReactions / usePresence inbound handling — as of 0.14.0
//    (hub#1497) the hooks parse the gateway-real action-frame envelopes
//    ({ type: 'chat', action: 'message'|'history' }, { type: 'reaction',
//    action: 'reaction_received', data }, { type: 'presence', action:
//    'subscribed'|'set'|'update'|'offline' }) payload-first, with the old
//    flat shapes (chat:message / chat:history / reaction:new /
//    reaction:history / presence:state / presence:joined / presence:updated
//    / presence:left) kept as a legacy fallback. EC's ws.chat.* /
//    ws.reaction.* declarations describe the gateway action-frame envelopes;
//    full inbound-envelope assertions remain TODO until EC declares the
//    complete send-back set (e.g. presence/update, reaction_received).
//
// c) Outbound frames with NO EC declaration yet (all gateway-verified
//    verbs, sent without `satisfies` annotations — EC backfill candidates):
//    chat/leave (useChat cleanup), reaction/subscribe + reaction/unsubscribe
//    (useReactions lifecycle).
//
// d) RESOLVED in EC v0.3.56 (hub#1497): client.activity.* now declares the
//    gateway-real `channelId` + 'getHistory' frames; the former
//    `_actHistDiverges` pin in §2 was replaced by the direct `_actHist`
//    assertion and useActivity.loadHistory regained its `satisfies`
//    annotation.
// ---------------------------------------------------------------------------

// ActivityEvent field shape vs EC's ws.activity.event payload (post-parse →
// pre-parse direction + key parity), envelope divergence notwithstanding.
type EcActivityEventPayload = RemoveIndex<EventPayloadMap['ws.activity.event']['payload']>;
type _activityKeys = Assert<SameKeys<ActivityEvent, EcActivityEventPayload>>;
type _activityFields = Assert<Extends<ActivityEvent, EcActivityEventPayload>>;

// Reaction core wire fields vs the legacy ws.reaction.received data block —
// partial check only (see divergence note b).
type EcReactionData = RemoveIndex<EventPayloadMap['ws.reaction.received']['data']>;
type _reactionCore = Assert<Extends<Reaction, EcReactionData>>;

// ChatMessage has no EC counterpart to assert against (divergence note b);
// referenced here so the import stays load-bearing if the type is renamed.
type _chatMessageStillExported = Assert<Extends<ChatMessage['id'], string>>;

// ---------------------------------------------------------------------------
// Runtime stub — keeps jest happy; the real assertions are the types above.
// A representative frame per service exercises that the EC types describe
// constructible values (and that the type-only imports erased at runtime).
// ---------------------------------------------------------------------------

describe('contract conformance (compile-time)', () => {
  it('EC client-frame payloads are constructible from hook frame shapes', () => {
    const chatSend: ClientFramePayload<'client.chat.send'> = {
      service: 'chat',
      action: 'send',
      channel: 'chat:general',
      message: 'hello',
    };
    const reactionSend: ClientFramePayload<'client.reaction.send'> = {
      service: 'reaction',
      action: 'send',
      channel: 'chat:general',
      emoji: '🔥',
    };
    const resub: ClientFramePayload<'client.subscribe.subscribe'> = {
      service: 'subscribe',
      action: 'subscribe',
      channel: 'doc:readme',
    };
    expect(chatSend.service).toBe('chat');
    expect(reactionSend.action).toBe('send');
    expect(resub.channel).toBe('doc:readme');
  });

  it('type-only event-catalog imports leave no runtime require', () => {
    // If the import at the top of this file were not type-only, jest's
    // module registry would contain the EC package after loading this file.
    const ecRuntime = Object.keys(require.cache).filter((k) =>
      k.includes(`${'@connorhoehn'}/event-catalog`),
    );
    expect(ecRuntime).toEqual([]);
  });
});
